### ISSUE TITLE
Adding license

### ISSUE THREAD

**Issue by abhishekpadalkar** [b-it-bots/mas_cartesian_control#1]
We are releasing this package as standard ROS package in kinetic. For that we need to add an appropriate license. I will go for BSD or Apache. Please help me deciding the license. Please read this comment : https://github.com/ros/rosdistro/pull/23132 .

**Comment by alex-mitrevski** [comment]
I think BSD should be fine. I've opened a PR adding the license; let's wait for @sthoduka and @deebuls to take a look.
